name = "demo"
compatibility_date = "2022-05-13"
compatibility_flags = ["streams_enable_constructors"]

[build]
command = "npm run esbuild:worker"

[site]
entry-point = "./dist/client/_worker.js"
bucket = "./dist/client"

